export const studentList = [{
    ID:1,
    name: 'Ramakrishna Vara Prasad',
    surname: 'channagiri',
    // description: 'Although Colvin is predominantly known for abstract themes that allude to pre-Hispanic symbols, this gigantic sculpture, an homage to neurosurgery, is one of her most recognizable public art pieces.',
    url: 'https://i.imgur.com/Mx7dA2Y.jpg',
    alt: 'A bronze statue of two crossed hands delicately holding a human brain in their fingertips.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:2,
    name: 'Geethika',
    surname: 'ponnur',
    // description: 'This enormous (75 ft. or 23m) silver flower is located in Buenos Aires. It is designed to move, closing its petals in the evening or when strong winds blow and opening them in the morning.',
    url: 'https://i.imgur.com/ZF6s192m.jpg',
    alt: 'A gigantic metallic flower sculpture with reflective mirror-like petals and strong stamens.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:3,
    name: 'Likhith',
    surname: 'channagiri',
    // description: 'Wilson was known for his preoccupation with equality, social justice, as well as the essential and spiritual qualities of humankind. This massive (7ft. or 2,13m) bronze represents what he described as "a symbolic Black presence infused with a sense of universal humanity."',
    url: 'https://i.imgur.com/aTtVpES.jpg',
    alt: 'The sculpture depicting a human head seems ever-present and solemn. It radiates calm and serenity.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:4,
    name: 'Megna',
    surname: 'ponnur',
    // description: 'Located on the Easter Island, there are 1,000 moai, or extant monumental statues, created by the early Rapa Nui people, which some believe represented deified ancestors.',
    url: 'https://i.imgur.com/RCwLEoQm.jpg',
    alt: 'Three monumental stone busts with the heads that are disproportionately large with somber faces.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:5,
    name: 'Likhita',
    surname: 'channagiri',
    // description: 'The Nanas are triumphant creatures, symbols of femininity and maternity. Initially, Saint Phalle used fabric and found objects for the Nanas, and later on introduced polyester to achieve a more vibrant effect.',
    url: 'https://i.imgur.com/Sd1AgUOm.jpg',
    alt: 'A large mosaic sculpture of a whimsical dancing female figure in a colorful costume emanating joy.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:6,
    name: 'Dhanush',
    surname: 'Bontala',
    // description: 'This abstract bronze sculpture is a part of The Family of Man series located at Yorkshire Sculpture Park. Hepworth chose not to create literal representations of the world but developed abstract forms inspired by people and landscapes.',
    url: 'https://i.imgur.com/2heNQDcm.jpg',
    alt: 'A tall sculpture made of three elements stacked on each other reminding of a human figure.',
    marks1:70,
    marks2:60,
    marks3:65,
  },{
    ID:7,
    name: 'Ramakrishna Vara Prasad',
    surname: 'channagiri',
    // description: 'Although Colvin is predominantly known for abstract themes that allude to pre-Hispanic symbols, this gigantic sculpture, an homage to neurosurgery, is one of her most recognizable public art pieces.',
    url: 'https://i.imgur.com/Mx7dA2Y.jpg',
    alt: 'A bronze statue of two crossed hands delicately holding a human brain in their fingertips.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:8,
    name: 'Geethika',
    surname: 'ponnur',
    // description: 'This enormous (75 ft. or 23m) silver flower is located in Buenos Aires. It is designed to move, closing its petals in the evening or when strong winds blow and opening them in the morning.',
    url: 'https://i.imgur.com/ZF6s192m.jpg',
    alt: 'A gigantic metallic flower sculpture with reflective mirror-like petals and strong stamens.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:9,
    name: 'Likhith',
    surname: 'channagiri',
    // description: 'Wilson was known for his preoccupation with equality, social justice, as well as the essential and spiritual qualities of humankind. This massive (7ft. or 2,13m) bronze represents what he described as "a symbolic Black presence infused with a sense of universal humanity."',
    url: 'https://i.imgur.com/aTtVpES.jpg',
    alt: 'The sculpture depicting a human head seems ever-present and solemn. It radiates calm and serenity.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:10,
    name: 'Megna',
    surname: 'ponnur',
    // description: 'Located on the Easter Island, there are 1,000 moai, or extant monumental statues, created by the early Rapa Nui people, which some believe represented deified ancestors.',
    url: 'https://i.imgur.com/RCwLEoQm.jpg',
    alt: 'Three monumental stone busts with the heads that are disproportionately large with somber faces.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:11,
    name: 'Likhita',
    surname: 'channagiri',
    // description: 'The Nanas are triumphant creatures, symbols of femininity and maternity. Initially, Saint Phalle used fabric and found objects for the Nanas, and later on introduced polyester to achieve a more vibrant effect.',
    url: 'https://i.imgur.com/Sd1AgUOm.jpg',
    alt: 'A large mosaic sculpture of a whimsical dancing female figure in a colorful costume emanating joy.',
    marks1:70,
    marks2:60,
    marks3:65,
  }, {
    ID:12,
    name: 'Dhanush',
    surname: 'Bontala',
    // description: 'This abstract bronze sculpture is a part of The Family of Man series located at Yorkshire Sculpture Park. Hepworth chose not to create literal representations of the world but developed abstract forms inspired by people and landscapes.',
    url: 'https://i.imgur.com/2heNQDcm.jpg',
    alt: 'A tall sculpture made of three elements stacked on each other reminding of a human figure.',
    marks1:70,
    marks2:60,
    marks3:65,
  },];
  